### ISSUE TITLE
Support PostgreSQL10

### ISSUE THREAD

**Issue by octaltree** [subzerocloud/postgrest-starter-kit#41]
Hi,

PostgreSQL 10 improves interesting features.
[PostgreSQL: PostgreSQL 10 Released](https://www.postgresql.org/about/news/1786/)

postgrest says
> PostgreSQL version 9.5 or greater is required

Would you update docker-compose.yml and test?
```
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
```
